### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-mana#2]
[PRACTICA_1_Equipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-mana/files/10750798/PRACTICA_1_Equipo.pdf)

https://www.figma.com/file/j3UuORq3CUItmNuFkCkfXO/CARTA-DE-RESTAURANTE?node-id=0%3A1&t=S9TeIYQpw2cAzVED-0

**Comment by RicardoMtzSts** [comment]
Practica 1 reporte: Portada: 25 puntos.
procedimiento: 25 puntos.
figura, ilustración y fotografia:25 puntos. 
Resultado y conclusiones: 25 puntos.
Total: 100/100
porcentaje: 20%

Magnifico excelente trabajo sigan así.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
